version: '3.8'

services:
  gsm-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gsm_matrix_core
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - TZ=Europe/Istanbul
      - PORT=8080
      - ENV=production
      - DATABASE_URL=postgres://postgres:wzfvbo047begspmu@gsm-postgresql-uw0km3:5432/postgres?sslmode=disable
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URL=${GOOGLE_REDIRECT_URL}
      - JWT_SECRET=${JWT_SECRET}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - gsm-network

networks:
  gsm-network:
    driver: bridge
